using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class BG_Class_Stat : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Class_Stat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Class_Stat(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4847391676627377824UL,1091868984838257303UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.Single bg_STR
	{
		get => _bg_STR[Index];
		set => _bg_STR[Index] = value;
	}
	public System.Single bg_HLT
	{
		get => _bg_HLT[Index];
		set => _bg_HLT[Index] = value;
	}
	public System.Single bg_DEF
	{
		get => _bg_DEF[Index];
		set => _bg_DEF[Index] = value;
	}
	public System.Single bg_ACR
	{
		get => _bg_ACR[Index];
		set => _bg_ACR[Index] = value;
	}
	public System.Single bg_AGI
	{
		get => _bg_AGI[Index];
		set => _bg_AGI[Index] = value;
	}
	public System.Single bg_CRT
	{
		get => _bg_CRT[Index];
		set => _bg_CRT[Index] = value;
	}
	public System.Int32 bg_ACT
	{
		get => _bg_ACT[Index];
		set => _bg_ACT[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5663607984770084405UL,16608334719393682572UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_STR
	{
		get
		{

			if(_ufle12jhs77_bg_STR == null)
			{
				_ufle12jhs77_bg_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4613400273432549076UL,4004705258236064913UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STR != null) _ufle12jhs77_bg_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STR = null;
				}
				_ufle12jhs77_bg_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_HLT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_HLT
	{
		get
		{

			if(_ufle12jhs77_bg_HLT == null)
			{
				_ufle12jhs77_bg_HLT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5012602710175078431UL,10191402814628584874UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_HLT != null) _ufle12jhs77_bg_HLT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_HLT = null;
				}
				_ufle12jhs77_bg_HLT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_HLT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_DEF;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_DEF
	{
		get
		{

			if(_ufle12jhs77_bg_DEF == null)
			{
				_ufle12jhs77_bg_DEF = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5674644854609239821UL,6293603214591918779UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_DEF != null) _ufle12jhs77_bg_DEF.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_DEF = null;
				}
				_ufle12jhs77_bg_DEF.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_DEF;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_ACR == null)
			{
				_ufle12jhs77_bg_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5135824569123286765UL,10079325496234506655UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACR != null) _ufle12jhs77_bg_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACR = null;
				}
				_ufle12jhs77_bg_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_AGI;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_AGI
	{
		get
		{

			if(_ufle12jhs77_bg_AGI == null)
			{
				_ufle12jhs77_bg_AGI = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5171613487052230575UL,9867380411054793862UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_AGI != null) _ufle12jhs77_bg_AGI.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_AGI = null;
				}
				_ufle12jhs77_bg_AGI.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_AGI;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_CRT == null)
			{
				_ufle12jhs77_bg_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5539262436811629502UL,3456542650761169064UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_CRT != null) _ufle12jhs77_bg_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_CRT = null;
				}
				_ufle12jhs77_bg_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_bg_ACT;
	public static BansheeGz.BGDatabase.BGFieldInt _bg_ACT
	{
		get
		{

			if(_ufle12jhs77_bg_ACT == null)
			{
				_ufle12jhs77_bg_ACT = (BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5581460712161928207UL,17036170707586342302UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACT != null) _ufle12jhs77_bg_ACT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACT = null;
				}
				_ufle12jhs77_bg_ACT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACT;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Class_Stat() : base(MetaDefault)
	{
	}
	private BG_Class_Stat(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Class_Stat(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Class_Stat(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Class_Stat FindEntity(Predicate<BG_Class_Stat> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Class_Stat) entity)) as BG_Class_Stat;
	public static List<BG_Class_Stat> FindEntities(Predicate<BG_Class_Stat> filter, List<BG_Class_Stat> result=null, Comparison<BG_Class_Stat> sort=null)
	{
		result = result ?? new List<BG_Class_Stat>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Class_Stat) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Class_Stat) e1, (BG_Class_Stat) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Class_Stat) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Class_Stat> action, Predicate<BG_Class_Stat> filter=null, Comparison<BG_Class_Stat> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Class_Stat) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Class_Stat) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Class_Stat)e1,(BG_Class_Stat)e2));
	public static BG_Class_Stat GetEntity(BGId entityId) => (BG_Class_Stat) MetaDefault.GetEntity(entityId);
	public static BG_Class_Stat GetEntity(int index) => (BG_Class_Stat) MetaDefault[index];
	public static BG_Class_Stat GetEntity(string entityName) => (BG_Class_Stat) MetaDefault.GetEntity(entityName);
	public static BG_Class_Stat NewEntity() => (BG_Class_Stat) MetaDefault.NewEntity();
	public static BG_Class_Stat NewEntity(BGId entityId) => (BG_Class_Stat) MetaDefault.NewEntity(entityId);
}

public partial class BG_Class_Skill_Knight : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Class_Skill_Knight(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Class_Skill_Knight(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4950220822160698176UL,11787014897305900930UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.String bg_Type
	{
		get => _bg_Type[Index];
		set => _bg_Type[Index] = value;
	}
	public System.Single bg_STR
	{
		get => _bg_STR[Index];
		set => _bg_STR[Index] = value;
	}
	public System.Single bg_ACR
	{
		get => _bg_ACR[Index];
		set => _bg_ACR[Index] = value;
	}
	public System.Single bg_CRT
	{
		get => _bg_CRT[Index];
		set => _bg_CRT[Index] = value;
	}
	public System.String bg_STATUS
	{
		get => _bg_STATUS[Index];
		set => _bg_STATUS[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5389588275252221899UL,5478175360645708192UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Type;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Type
	{
		get
		{

			if(_ufle12jhs77_bg_Type == null)
			{
				_ufle12jhs77_bg_Type = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4694689398269910142UL,10681006378884063360UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Type != null) _ufle12jhs77_bg_Type.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Type = null;
				}
				_ufle12jhs77_bg_Type.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Type;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_STR
	{
		get
		{

			if(_ufle12jhs77_bg_STR == null)
			{
				_ufle12jhs77_bg_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4876023653306745366UL,5925637572947134123UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STR != null) _ufle12jhs77_bg_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STR = null;
				}
				_ufle12jhs77_bg_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_ACR == null)
			{
				_ufle12jhs77_bg_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5266642306262101336UL,15543660175833111178UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACR != null) _ufle12jhs77_bg_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACR = null;
				}
				_ufle12jhs77_bg_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_CRT == null)
			{
				_ufle12jhs77_bg_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5614634933984009950UL,13045940056860214432UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_CRT != null) _ufle12jhs77_bg_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_CRT = null;
				}
				_ufle12jhs77_bg_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_STATUS;
	public static BansheeGz.BGDatabase.BGFieldString _bg_STATUS
	{
		get
		{

			if(_ufle12jhs77_bg_STATUS == null)
			{
				_ufle12jhs77_bg_STATUS = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4925391671248946778UL,3380681328251769989UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STATUS != null) _ufle12jhs77_bg_STATUS.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STATUS = null;
				}
				_ufle12jhs77_bg_STATUS.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STATUS;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Class_Skill_Knight() : base(MetaDefault)
	{
	}
	private BG_Class_Skill_Knight(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Class_Skill_Knight(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Class_Skill_Knight(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Class_Skill_Knight FindEntity(Predicate<BG_Class_Skill_Knight> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Class_Skill_Knight) entity)) as BG_Class_Skill_Knight;
	public static List<BG_Class_Skill_Knight> FindEntities(Predicate<BG_Class_Skill_Knight> filter, List<BG_Class_Skill_Knight> result=null, Comparison<BG_Class_Skill_Knight> sort=null)
	{
		result = result ?? new List<BG_Class_Skill_Knight>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Class_Skill_Knight) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Class_Skill_Knight) e1, (BG_Class_Skill_Knight) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Class_Skill_Knight) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Class_Skill_Knight> action, Predicate<BG_Class_Skill_Knight> filter=null, Comparison<BG_Class_Skill_Knight> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Class_Skill_Knight) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Class_Skill_Knight) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Class_Skill_Knight)e1,(BG_Class_Skill_Knight)e2));
	public static BG_Class_Skill_Knight GetEntity(BGId entityId) => (BG_Class_Skill_Knight) MetaDefault.GetEntity(entityId);
	public static BG_Class_Skill_Knight GetEntity(int index) => (BG_Class_Skill_Knight) MetaDefault[index];
	public static BG_Class_Skill_Knight GetEntity(string entityName) => (BG_Class_Skill_Knight) MetaDefault.GetEntity(entityName);
	public static BG_Class_Skill_Knight NewEntity() => (BG_Class_Skill_Knight) MetaDefault.NewEntity();
	public static BG_Class_Skill_Knight NewEntity(BGId entityId) => (BG_Class_Skill_Knight) MetaDefault.NewEntity(entityId);
}

public partial class BG_Class_Skill_Status : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Class_Skill_Status(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Class_Skill_Status(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4867977275272598753UL,11877203867741625515UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.String bg_Type
	{
		get => _bg_Type[Index];
		set => _bg_Type[Index] = value;
	}
	public System.Single bg_STR
	{
		get => _bg_STR[Index];
		set => _bg_STR[Index] = value;
	}
	public System.Single bg_HLT
	{
		get => _bg_HLT[Index];
		set => _bg_HLT[Index] = value;
	}
	public System.Single bg_DEF
	{
		get => _bg_DEF[Index];
		set => _bg_DEF[Index] = value;
	}
	public System.Single bg_ACR
	{
		get => _bg_ACR[Index];
		set => _bg_ACR[Index] = value;
	}
	public System.Single bg_AGI
	{
		get => _bg_AGI[Index];
		set => _bg_AGI[Index] = value;
	}
	public System.Single bg_CRT
	{
		get => _bg_CRT[Index];
		set => _bg_CRT[Index] = value;
	}
	public System.Int32 bg_ACT
	{
		get => _bg_ACT[Index];
		set => _bg_ACT[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5151774736850616967UL,1340393035150268817UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Type;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Type
	{
		get
		{

			if(_ufle12jhs77_bg_Type == null)
			{
				_ufle12jhs77_bg_Type = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5193114290934921139UL,1316252453019176864UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Type != null) _ufle12jhs77_bg_Type.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Type = null;
				}
				_ufle12jhs77_bg_Type.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Type;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_STR
	{
		get
		{

			if(_ufle12jhs77_bg_STR == null)
			{
				_ufle12jhs77_bg_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5444664305079248112UL,11436920241196975018UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STR != null) _ufle12jhs77_bg_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STR = null;
				}
				_ufle12jhs77_bg_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_HLT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_HLT
	{
		get
		{

			if(_ufle12jhs77_bg_HLT == null)
			{
				_ufle12jhs77_bg_HLT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5125521002040063340UL,11829561999759151749UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_HLT != null) _ufle12jhs77_bg_HLT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_HLT = null;
				}
				_ufle12jhs77_bg_HLT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_HLT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_DEF;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_DEF
	{
		get
		{

			if(_ufle12jhs77_bg_DEF == null)
			{
				_ufle12jhs77_bg_DEF = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5022367105882797968UL,8279049316160775553UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_DEF != null) _ufle12jhs77_bg_DEF.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_DEF = null;
				}
				_ufle12jhs77_bg_DEF.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_DEF;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_ACR == null)
			{
				_ufle12jhs77_bg_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4951686447542852554UL,17186205207189696157UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACR != null) _ufle12jhs77_bg_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACR = null;
				}
				_ufle12jhs77_bg_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_AGI;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_AGI
	{
		get
		{

			if(_ufle12jhs77_bg_AGI == null)
			{
				_ufle12jhs77_bg_AGI = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5724347118774140488UL,7438370827810313622UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_AGI != null) _ufle12jhs77_bg_AGI.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_AGI = null;
				}
				_ufle12jhs77_bg_AGI.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_AGI;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_CRT == null)
			{
				_ufle12jhs77_bg_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5078343147105345050UL,4819842443432132011UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_CRT != null) _ufle12jhs77_bg_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_CRT = null;
				}
				_ufle12jhs77_bg_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_bg_ACT;
	public static BansheeGz.BGDatabase.BGFieldInt _bg_ACT
	{
		get
		{

			if(_ufle12jhs77_bg_ACT == null)
			{
				_ufle12jhs77_bg_ACT = (BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5289887246621330483UL,17609025045007819445UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACT != null) _ufle12jhs77_bg_ACT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACT = null;
				}
				_ufle12jhs77_bg_ACT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACT;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Class_Skill_Status() : base(MetaDefault)
	{
	}
	private BG_Class_Skill_Status(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Class_Skill_Status(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Class_Skill_Status(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Class_Skill_Status FindEntity(Predicate<BG_Class_Skill_Status> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Class_Skill_Status) entity)) as BG_Class_Skill_Status;
	public static List<BG_Class_Skill_Status> FindEntities(Predicate<BG_Class_Skill_Status> filter, List<BG_Class_Skill_Status> result=null, Comparison<BG_Class_Skill_Status> sort=null)
	{
		result = result ?? new List<BG_Class_Skill_Status>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Class_Skill_Status) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Class_Skill_Status) e1, (BG_Class_Skill_Status) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Class_Skill_Status) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Class_Skill_Status> action, Predicate<BG_Class_Skill_Status> filter=null, Comparison<BG_Class_Skill_Status> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Class_Skill_Status) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Class_Skill_Status) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Class_Skill_Status)e1,(BG_Class_Skill_Status)e2));
	public static BG_Class_Skill_Status GetEntity(BGId entityId) => (BG_Class_Skill_Status) MetaDefault.GetEntity(entityId);
	public static BG_Class_Skill_Status GetEntity(int index) => (BG_Class_Skill_Status) MetaDefault[index];
	public static BG_Class_Skill_Status GetEntity(string entityName) => (BG_Class_Skill_Status) MetaDefault.GetEntity(entityName);
	public static BG_Class_Skill_Status NewEntity() => (BG_Class_Skill_Status) MetaDefault.NewEntity();
	public static BG_Class_Skill_Status NewEntity(BGId entityId) => (BG_Class_Skill_Status) MetaDefault.NewEntity(entityId);
}

public partial class BG_Monster_Stat : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Monster_Stat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Monster_Stat(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4778752890207145539UL,15679640458538626955UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.Single bg_STR
	{
		get => _bg_STR[Index];
		set => _bg_STR[Index] = value;
	}
	public System.Single bg_HLT
	{
		get => _bg_HLT[Index];
		set => _bg_HLT[Index] = value;
	}
	public System.Single bg_DEF
	{
		get => _bg_DEF[Index];
		set => _bg_DEF[Index] = value;
	}
	public System.Single bg_ACR
	{
		get => _bg_ACR[Index];
		set => _bg_ACR[Index] = value;
	}
	public System.Single bg_AGI
	{
		get => _bg_AGI[Index];
		set => _bg_AGI[Index] = value;
	}
	public System.Single bg_CRT
	{
		get => _bg_CRT[Index];
		set => _bg_CRT[Index] = value;
	}
	public System.Int32 bg_ACT
	{
		get => _bg_ACT[Index];
		set => _bg_ACT[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5315993532988344589UL,17190012791736833467UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_STR
	{
		get
		{

			if(_ufle12jhs77_bg_STR == null)
			{
				_ufle12jhs77_bg_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5153453044494646722UL,15509736263476739732UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STR != null) _ufle12jhs77_bg_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STR = null;
				}
				_ufle12jhs77_bg_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_HLT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_HLT
	{
		get
		{

			if(_ufle12jhs77_bg_HLT == null)
			{
				_ufle12jhs77_bg_HLT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5235346905205474462UL,399950511263329703UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_HLT != null) _ufle12jhs77_bg_HLT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_HLT = null;
				}
				_ufle12jhs77_bg_HLT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_HLT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_DEF;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_DEF
	{
		get
		{

			if(_ufle12jhs77_bg_DEF == null)
			{
				_ufle12jhs77_bg_DEF = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5354155939769252414UL,17429660077083034036UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_DEF != null) _ufle12jhs77_bg_DEF.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_DEF = null;
				}
				_ufle12jhs77_bg_DEF.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_DEF;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_ACR == null)
			{
				_ufle12jhs77_bg_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5696254635894070397UL,8126713265468049038UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACR != null) _ufle12jhs77_bg_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACR = null;
				}
				_ufle12jhs77_bg_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_AGI;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_AGI
	{
		get
		{

			if(_ufle12jhs77_bg_AGI == null)
			{
				_ufle12jhs77_bg_AGI = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5577572009307325562UL,13648096510533203623UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_AGI != null) _ufle12jhs77_bg_AGI.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_AGI = null;
				}
				_ufle12jhs77_bg_AGI.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_AGI;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_CRT == null)
			{
				_ufle12jhs77_bg_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4664661018011856615UL,15830739772319060899UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_CRT != null) _ufle12jhs77_bg_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_CRT = null;
				}
				_ufle12jhs77_bg_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_bg_ACT;
	public static BansheeGz.BGDatabase.BGFieldInt _bg_ACT
	{
		get
		{

			if(_ufle12jhs77_bg_ACT == null)
			{
				_ufle12jhs77_bg_ACT = (BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4918808040266275022UL,15669221509353842818UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACT != null) _ufle12jhs77_bg_ACT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACT = null;
				}
				_ufle12jhs77_bg_ACT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACT;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Monster_Stat() : base(MetaDefault)
	{
	}
	private BG_Monster_Stat(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Monster_Stat(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Monster_Stat(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Monster_Stat FindEntity(Predicate<BG_Monster_Stat> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Monster_Stat) entity)) as BG_Monster_Stat;
	public static List<BG_Monster_Stat> FindEntities(Predicate<BG_Monster_Stat> filter, List<BG_Monster_Stat> result=null, Comparison<BG_Monster_Stat> sort=null)
	{
		result = result ?? new List<BG_Monster_Stat>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Monster_Stat) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Monster_Stat) e1, (BG_Monster_Stat) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Monster_Stat) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Monster_Stat> action, Predicate<BG_Monster_Stat> filter=null, Comparison<BG_Monster_Stat> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Monster_Stat) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Monster_Stat) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Monster_Stat)e1,(BG_Monster_Stat)e2));
	public static BG_Monster_Stat GetEntity(BGId entityId) => (BG_Monster_Stat) MetaDefault.GetEntity(entityId);
	public static BG_Monster_Stat GetEntity(int index) => (BG_Monster_Stat) MetaDefault[index];
	public static BG_Monster_Stat GetEntity(string entityName) => (BG_Monster_Stat) MetaDefault.GetEntity(entityName);
	public static BG_Monster_Stat NewEntity() => (BG_Monster_Stat) MetaDefault.NewEntity();
	public static BG_Monster_Stat NewEntity(BGId entityId) => (BG_Monster_Stat) MetaDefault.NewEntity(entityId);
}

public partial class BG_Monster_Part_Stat : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Monster_Part_Stat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Monster_Part_Stat(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5615409367230731981UL,6348447941710603149UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.Single bg_Part_HLT
	{
		get => _bg_Part_HLT[Index];
		set => _bg_Part_HLT[Index] = value;
	}
	public System.Single bg_Part_DEF
	{
		get => _bg_Part_DEF[Index];
		set => _bg_Part_DEF[Index] = value;
	}
	public System.Single bg_Part_AGI
	{
		get => _bg_Part_AGI[Index];
		set => _bg_Part_AGI[Index] = value;
	}
	public System.String bg_GMCK
	{
		get => _bg_GMCK[Index];
		set => _bg_GMCK[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4952700472540267087UL,634640027203676303UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Part_HLT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Part_HLT
	{
		get
		{

			if(_ufle12jhs77_bg_Part_HLT == null)
			{
				_ufle12jhs77_bg_Part_HLT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5251664795031497047UL,10974860221144645547UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Part_HLT != null) _ufle12jhs77_bg_Part_HLT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Part_HLT = null;
				}
				_ufle12jhs77_bg_Part_HLT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Part_HLT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Part_DEF;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Part_DEF
	{
		get
		{

			if(_ufle12jhs77_bg_Part_DEF == null)
			{
				_ufle12jhs77_bg_Part_DEF = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5452017415408477360UL,17795843376821314494UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Part_DEF != null) _ufle12jhs77_bg_Part_DEF.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Part_DEF = null;
				}
				_ufle12jhs77_bg_Part_DEF.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Part_DEF;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Part_AGI;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Part_AGI
	{
		get
		{

			if(_ufle12jhs77_bg_Part_AGI == null)
			{
				_ufle12jhs77_bg_Part_AGI = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4644197310534801890UL,18216192897476301998UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Part_AGI != null) _ufle12jhs77_bg_Part_AGI.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Part_AGI = null;
				}
				_ufle12jhs77_bg_Part_AGI.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Part_AGI;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_GMCK;
	public static BansheeGz.BGDatabase.BGFieldString _bg_GMCK
	{
		get
		{

			if(_ufle12jhs77_bg_GMCK == null)
			{
				_ufle12jhs77_bg_GMCK = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5262105110487494636UL,414752495935832486UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_GMCK != null) _ufle12jhs77_bg_GMCK.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_GMCK = null;
				}
				_ufle12jhs77_bg_GMCK.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_GMCK;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Monster_Part_Stat() : base(MetaDefault)
	{
	}
	private BG_Monster_Part_Stat(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Monster_Part_Stat(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Monster_Part_Stat(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Monster_Part_Stat FindEntity(Predicate<BG_Monster_Part_Stat> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Monster_Part_Stat) entity)) as BG_Monster_Part_Stat;
	public static List<BG_Monster_Part_Stat> FindEntities(Predicate<BG_Monster_Part_Stat> filter, List<BG_Monster_Part_Stat> result=null, Comparison<BG_Monster_Part_Stat> sort=null)
	{
		result = result ?? new List<BG_Monster_Part_Stat>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Monster_Part_Stat) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Monster_Part_Stat) e1, (BG_Monster_Part_Stat) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Monster_Part_Stat) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Monster_Part_Stat> action, Predicate<BG_Monster_Part_Stat> filter=null, Comparison<BG_Monster_Part_Stat> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Monster_Part_Stat) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Monster_Part_Stat) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Monster_Part_Stat)e1,(BG_Monster_Part_Stat)e2));
	public static BG_Monster_Part_Stat GetEntity(BGId entityId) => (BG_Monster_Part_Stat) MetaDefault.GetEntity(entityId);
	public static BG_Monster_Part_Stat GetEntity(int index) => (BG_Monster_Part_Stat) MetaDefault[index];
	public static BG_Monster_Part_Stat GetEntity(string entityName) => (BG_Monster_Part_Stat) MetaDefault.GetEntity(entityName);
	public static BG_Monster_Part_Stat NewEntity() => (BG_Monster_Part_Stat) MetaDefault.NewEntity();
	public static BG_Monster_Part_Stat NewEntity(BGId entityId) => (BG_Monster_Part_Stat) MetaDefault.NewEntity(entityId);
}

public partial class BG_Monster_Skill : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Monster_Skill(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Monster_Skill(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5398565994723864258UL,12143281923416310174UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.String bg_Skill_Type
	{
		get => _bg_Skill_Type[Index];
		set => _bg_Skill_Type[Index] = value;
	}
	public System.String bg_Skill_Work
	{
		get => _bg_Skill_Work[Index];
		set => _bg_Skill_Work[Index] = value;
	}
	public System.Single bg_Skill_STR
	{
		get => _bg_Skill_STR[Index];
		set => _bg_Skill_STR[Index] = value;
	}
	public System.Single bg_Skill_ACR
	{
		get => _bg_Skill_ACR[Index];
		set => _bg_Skill_ACR[Index] = value;
	}
	public System.Single bg_Skill_CRT
	{
		get => _bg_Skill_CRT[Index];
		set => _bg_Skill_CRT[Index] = value;
	}
	public System.Int32 bg_Skill_ACT
	{
		get => _bg_Skill_ACT[Index];
		set => _bg_Skill_ACT[Index] = value;
	}
	public System.String bg_GMCK
	{
		get => _bg_GMCK[Index];
		set => _bg_GMCK[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5380089727545036833UL,4342360978244784829UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Skill_Type;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Skill_Type
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_Type == null)
			{
				_ufle12jhs77_bg_Skill_Type = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5402326993571331921UL,10051222516803026613UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_Type != null) _ufle12jhs77_bg_Skill_Type.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_Type = null;
				}
				_ufle12jhs77_bg_Skill_Type.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_Type;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Skill_Work;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Skill_Work
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_Work == null)
			{
				_ufle12jhs77_bg_Skill_Work = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5251172163602676789UL,12273231655485758094UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_Work != null) _ufle12jhs77_bg_Skill_Work.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_Work = null;
				}
				_ufle12jhs77_bg_Skill_Work.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_Work;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Skill_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Skill_STR
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_STR == null)
			{
				_ufle12jhs77_bg_Skill_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4870808473354921203UL,10242334814190027693UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_STR != null) _ufle12jhs77_bg_Skill_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_STR = null;
				}
				_ufle12jhs77_bg_Skill_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Skill_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Skill_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_ACR == null)
			{
				_ufle12jhs77_bg_Skill_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5420778809440796789UL,10821640443747404450UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_ACR != null) _ufle12jhs77_bg_Skill_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_ACR = null;
				}
				_ufle12jhs77_bg_Skill_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_Skill_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_Skill_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_CRT == null)
			{
				_ufle12jhs77_bg_Skill_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5095881589798416471UL,6985794188328524699UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_CRT != null) _ufle12jhs77_bg_Skill_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_CRT = null;
				}
				_ufle12jhs77_bg_Skill_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_bg_Skill_ACT;
	public static BansheeGz.BGDatabase.BGFieldInt _bg_Skill_ACT
	{
		get
		{

			if(_ufle12jhs77_bg_Skill_ACT == null)
			{
				_ufle12jhs77_bg_Skill_ACT = (BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5536297334868094114UL,4762687783204217482UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Skill_ACT != null) _ufle12jhs77_bg_Skill_ACT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Skill_ACT = null;
				}
				_ufle12jhs77_bg_Skill_ACT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Skill_ACT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_GMCK;
	public static BansheeGz.BGDatabase.BGFieldString _bg_GMCK
	{
		get
		{

			if(_ufle12jhs77_bg_GMCK == null)
			{
				_ufle12jhs77_bg_GMCK = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5203430345981082889UL,4959983369144710017UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_GMCK != null) _ufle12jhs77_bg_GMCK.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_GMCK = null;
				}
				_ufle12jhs77_bg_GMCK.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_GMCK;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Monster_Skill() : base(MetaDefault)
	{
	}
	private BG_Monster_Skill(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Monster_Skill(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Monster_Skill(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Monster_Skill FindEntity(Predicate<BG_Monster_Skill> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Monster_Skill) entity)) as BG_Monster_Skill;
	public static List<BG_Monster_Skill> FindEntities(Predicate<BG_Monster_Skill> filter, List<BG_Monster_Skill> result=null, Comparison<BG_Monster_Skill> sort=null)
	{
		result = result ?? new List<BG_Monster_Skill>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Monster_Skill) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Monster_Skill) e1, (BG_Monster_Skill) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Monster_Skill) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Monster_Skill> action, Predicate<BG_Monster_Skill> filter=null, Comparison<BG_Monster_Skill> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Monster_Skill) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Monster_Skill) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Monster_Skill)e1,(BG_Monster_Skill)e2));
	public static BG_Monster_Skill GetEntity(BGId entityId) => (BG_Monster_Skill) MetaDefault.GetEntity(entityId);
	public static BG_Monster_Skill GetEntity(int index) => (BG_Monster_Skill) MetaDefault[index];
	public static BG_Monster_Skill GetEntity(string entityName) => (BG_Monster_Skill) MetaDefault.GetEntity(entityName);
	public static BG_Monster_Skill NewEntity() => (BG_Monster_Skill) MetaDefault.NewEntity();
	public static BG_Monster_Skill NewEntity(BGId entityId) => (BG_Monster_Skill) MetaDefault.NewEntity(entityId);
}

public partial class BG_Encounter : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Encounter(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Encounter(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5707897800009130532UL,15245694467969225363UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.Int32 bg_Num
	{
		get => _bg_Num[Index];
		set => _bg_Num[Index] = value;
	}
	public System.String bg_Row1
	{
		get => _bg_Row1[Index];
		set => _bg_Row1[Index] = value;
	}
	public System.String bg_Row2
	{
		get => _bg_Row2[Index];
		set => _bg_Row2[Index] = value;
	}
	public System.String bg_Row3
	{
		get => _bg_Row3[Index];
		set => _bg_Row3[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5232535849094540101UL,15262588739007229838UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_bg_Num;
	public static BansheeGz.BGDatabase.BGFieldInt _bg_Num
	{
		get
		{

			if(_ufle12jhs77_bg_Num == null)
			{
				_ufle12jhs77_bg_Num = (BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4783355648332687393UL,10512301411275458176UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Num != null) _ufle12jhs77_bg_Num.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Num = null;
				}
				_ufle12jhs77_bg_Num.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Num;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Row1;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Row1
	{
		get
		{

			if(_ufle12jhs77_bg_Row1 == null)
			{
				_ufle12jhs77_bg_Row1 = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5363703861899735298UL,8277456327509306526UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Row1 != null) _ufle12jhs77_bg_Row1.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Row1 = null;
				}
				_ufle12jhs77_bg_Row1.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Row1;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Row2;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Row2
	{
		get
		{

			if(_ufle12jhs77_bg_Row2 == null)
			{
				_ufle12jhs77_bg_Row2 = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4848681832918017171UL,11390861565492914851UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Row2 != null) _ufle12jhs77_bg_Row2.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Row2 = null;
				}
				_ufle12jhs77_bg_Row2.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Row2;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Row3;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Row3
	{
		get
		{

			if(_ufle12jhs77_bg_Row3 == null)
			{
				_ufle12jhs77_bg_Row3 = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4926140798965496781UL,8678729327026443168UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Row3 != null) _ufle12jhs77_bg_Row3.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Row3 = null;
				}
				_ufle12jhs77_bg_Row3.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Row3;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Encounter() : base(MetaDefault)
	{
	}
	private BG_Encounter(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Encounter(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Encounter(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Encounter FindEntity(Predicate<BG_Encounter> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Encounter) entity)) as BG_Encounter;
	public static List<BG_Encounter> FindEntities(Predicate<BG_Encounter> filter, List<BG_Encounter> result=null, Comparison<BG_Encounter> sort=null)
	{
		result = result ?? new List<BG_Encounter>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Encounter) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Encounter) e1, (BG_Encounter) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Encounter) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Encounter> action, Predicate<BG_Encounter> filter=null, Comparison<BG_Encounter> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Encounter) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Encounter) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Encounter)e1,(BG_Encounter)e2));
	public static BG_Encounter GetEntity(BGId entityId) => (BG_Encounter) MetaDefault.GetEntity(entityId);
	public static BG_Encounter GetEntity(int index) => (BG_Encounter) MetaDefault[index];
	public static BG_Encounter GetEntity(string entityName) => (BG_Encounter) MetaDefault.GetEntity(entityName);
	public static BG_Encounter NewEntity() => (BG_Encounter) MetaDefault.NewEntity();
	public static BG_Encounter NewEntity(BGId entityId) => (BG_Encounter) MetaDefault.NewEntity(entityId);
}

public partial class BG_Class_Skill_Nun : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_Class_Skill_Nun(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_Class_Skill_Nun(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{

			if(_metaDefault == null)
			{
				_metaDefault = BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4877420048058456456UL,10629741292704831678UL));
				void __Unloaded(BGObject f)
				{
					if(_metaDefault != null) _metaDefault.OnUnload -= __Unloaded;
					_metaDefault = null;
				}
				_metaDefault.OnUnload += __Unloaded;
			}
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String bg_name
	{
		get => _bg_name[Index];
		set => _bg_name[Index] = value;
	}
	public System.String bg_Type
	{
		get => _bg_Type[Index];
		set => _bg_Type[Index] = value;
	}
	public System.Single bg_STR
	{
		get => _bg_STR[Index];
		set => _bg_STR[Index] = value;
	}
	public System.Single bg_ACR
	{
		get => _bg_ACR[Index];
		set => _bg_ACR[Index] = value;
	}
	public System.Single bg_CRT
	{
		get => _bg_CRT[Index];
		set => _bg_CRT[Index] = value;
	}
	public System.String bg_STATUS
	{
		get => _bg_STATUS[Index];
		set => _bg_STATUS[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_bg_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _bg_name
	{
		get
		{

			if(_ufle12jhs77_bg_name == null)
			{
				_ufle12jhs77_bg_name = (BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4979651801801060624UL,7237037311175242647UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_name != null) _ufle12jhs77_bg_name.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_name = null;
				}
				_ufle12jhs77_bg_name.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_Type;
	public static BansheeGz.BGDatabase.BGFieldString _bg_Type
	{
		get
		{

			if(_ufle12jhs77_bg_Type == null)
			{
				_ufle12jhs77_bg_Type = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5360310438237490556UL,13993890499199135140UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_Type != null) _ufle12jhs77_bg_Type.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_Type = null;
				}
				_ufle12jhs77_bg_Type.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_Type;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_STR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_STR
	{
		get
		{

			if(_ufle12jhs77_bg_STR == null)
			{
				_ufle12jhs77_bg_STR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5132978782098780703UL,1160090936192306111UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STR != null) _ufle12jhs77_bg_STR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STR = null;
				}
				_ufle12jhs77_bg_STR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_ACR;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_ACR
	{
		get
		{

			if(_ufle12jhs77_bg_ACR == null)
			{
				_ufle12jhs77_bg_ACR = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5428722681667934271UL,4632944650196932235UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_ACR != null) _ufle12jhs77_bg_ACR.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_ACR = null;
				}
				_ufle12jhs77_bg_ACR.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_ACR;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_bg_CRT;
	public static BansheeGz.BGDatabase.BGFieldFloat _bg_CRT
	{
		get
		{

			if(_ufle12jhs77_bg_CRT == null)
			{
				_ufle12jhs77_bg_CRT = (BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5251577108210928113UL,6149146390428883084UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_CRT != null) _ufle12jhs77_bg_CRT.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_CRT = null;
				}
				_ufle12jhs77_bg_CRT.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_CRT;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_bg_STATUS;
	public static BansheeGz.BGDatabase.BGFieldString _bg_STATUS
	{
		get
		{

			if(_ufle12jhs77_bg_STATUS == null)
			{
				_ufle12jhs77_bg_STATUS = (BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5633894232329614167UL,6153298759072453255UL));
				void __Unloaded(BGObject f)
				{
					if(_ufle12jhs77_bg_STATUS != null) _ufle12jhs77_bg_STATUS.OnUnload -= __Unloaded;
					_ufle12jhs77_bg_STATUS = null;
				}
				_ufle12jhs77_bg_STATUS.OnUnload += __Unloaded;
			}
			return _ufle12jhs77_bg_STATUS;
		}
	}
	private static readonly BG_Class_Stat.Factory _factory0_PFS = new BG_Class_Stat.Factory();
	private static readonly BG_Class_Skill_Knight.Factory _factory1_PFS = new BG_Class_Skill_Knight.Factory();
	private static readonly BG_Class_Skill_Status.Factory _factory2_PFS = new BG_Class_Skill_Status.Factory();
	private static readonly BG_Monster_Stat.Factory _factory3_PFS = new BG_Monster_Stat.Factory();
	private static readonly BG_Monster_Part_Stat.Factory _factory4_PFS = new BG_Monster_Part_Stat.Factory();
	private static readonly BG_Monster_Skill.Factory _factory5_PFS = new BG_Monster_Skill.Factory();
	private static readonly BG_Encounter.Factory _factory6_PFS = new BG_Encounter.Factory();
	private static readonly BG_Class_Skill_Nun.Factory _factory7_PFS = new BG_Class_Skill_Nun.Factory();
	private BG_Class_Skill_Nun() : base(MetaDefault)
	{
	}
	private BG_Class_Skill_Nun(BGId id) : base(MetaDefault, id)
	{
	}
	private BG_Class_Skill_Nun(BGMetaEntity meta) : base(meta)
	{
	}
	private BG_Class_Skill_Nun(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BG_Class_Skill_Nun FindEntity(Predicate<BG_Class_Skill_Nun> filter) => MetaDefault.FindEntity(entity => filter==null || filter((BG_Class_Skill_Nun) entity)) as BG_Class_Skill_Nun;
	public static List<BG_Class_Skill_Nun> FindEntities(Predicate<BG_Class_Skill_Nun> filter, List<BG_Class_Skill_Nun> result=null, Comparison<BG_Class_Skill_Nun> sort=null)
	{
		result = result ?? new List<BG_Class_Skill_Nun>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BG_Class_Skill_Nun) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BG_Class_Skill_Nun) e1, (BG_Class_Skill_Nun) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BG_Class_Skill_Nun) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<BG_Class_Skill_Nun> action, Predicate<BG_Class_Skill_Nun> filter=null, Comparison<BG_Class_Skill_Nun> sort=null) => MetaDefault.ForEachEntity(entity => action((BG_Class_Skill_Nun) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BG_Class_Skill_Nun) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BG_Class_Skill_Nun)e1,(BG_Class_Skill_Nun)e2));
	public static BG_Class_Skill_Nun GetEntity(BGId entityId) => (BG_Class_Skill_Nun) MetaDefault.GetEntity(entityId);
	public static BG_Class_Skill_Nun GetEntity(int index) => (BG_Class_Skill_Nun) MetaDefault[index];
	public static BG_Class_Skill_Nun GetEntity(string entityName) => (BG_Class_Skill_Nun) MetaDefault.GetEntity(entityName);
	public static BG_Class_Skill_Nun NewEntity() => (BG_Class_Skill_Nun) MetaDefault.NewEntity();
	public static BG_Class_Skill_Nun NewEntity(BGId entityId) => (BG_Class_Skill_Nun) MetaDefault.NewEntity(entityId);
}
#pragma warning restore 414
